version: '3.9'

services:

  account:
    build: ./account
    container_name: go_rabbit__account
    restart: always
    ports:
      - 5010:5010
    env:
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - postgres

  # office:
  #   build: ./office
  #   container_name: go_rabbit__office
  #   restart: always
  #   ports:
  #     - 5020:5020
  #   # env_file:
  #   #   - ./office/.env
  #   depends_on:
  #     - rabbitmq
  #     - mongo
  #
  # products:
  #   build: ./products
  #   container_name: go_rabbit__products
  #   restart: always
  #   ports:
  #     - 5030:5030
  #   # env_file:
  #   #   - ./products/.env
  #   depends_on:
  #     - rabbitmq
  #     - mongo
  #
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: go_rabbit__rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

