version: '3.9'

services:

  account:
    build: ./account
    restart: always
    ports:
      - 5010:5010
    env_file:
      - ./account/.env
    depends_on:
      - rabbitmq
      - mongo

  office:
    build: ./office
    restart: always
    ports:
      - 5020:5020
    env_file:
      - ./office/.env
    depends_on:
      - rabbitmq
      - mongo

  products:
    build: ./products
    restart: always
    ports:
      - 5030:5030
    env_file:
      - ./products/.env
    depends_on:
      - rabbitmq
      - mongo

  mongo:
    image: mongo
    ports:
     - '27017:27017'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
