version: '3.9'

services:
  
  mongo:
    image: mongo
    ports:
     - '27017:27017'

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
